/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppArchiveRouteImport } from './routes/_app.archive'
import { Route as AppGroupsIndexRouteImport } from './routes/_app.groups.index'
import { Route as AppSettingsPaymentsRouteImport } from './routes/_app.settings.payments'
import { Route as AppGroupsNewRouteImport } from './routes/_app.groups.new'
import { Route as AppGroupsIdRouteImport } from './routes/_app.groups.$id'
import { Route as AppExpensesNewRouteImport } from './routes/_app.expenses.new'
import { Route as AppExpensesIdRouteImport } from './routes/_app.expenses.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppGroupsNewRoute = AppGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIdRoute = AppExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof AppArchiveRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/wallet': typeof AppWalletRoute
  '/share/$token': typeof ShareTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/groups/': typeof AppGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof AppArchiveRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/wallet': typeof AppWalletRoute
  '/share/$token': typeof ShareTokenRoute
  '/auth': typeof AuthIndexRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/groups': typeof AppGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/archive': typeof AppArchiveRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/wallet': typeof AppWalletRoute
  '/share/$token': typeof ShareTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/expenses/$id': typeof AppExpensesIdRoute
  '/_app/expenses/new': typeof AppExpensesNewRoute
  '/_app/groups/$id': typeof AppGroupsIdRoute
  '/_app/groups/new': typeof AppGroupsNewRoute
  '/_app/settings/payments': typeof AppSettingsPaymentsRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/share/$token'
    | '/auth/'
    | '/expenses/$id'
    | '/expenses/new'
    | '/groups/$id'
    | '/groups/new'
    | '/settings/payments'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/share/$token'
    | '/auth'
    | '/expenses/$id'
    | '/expenses/new'
    | '/groups/$id'
    | '/groups/new'
    | '/settings/payments'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/archive'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/wallet'
    | '/share/$token'
    | '/auth/'
    | '/_app/expenses/$id'
    | '/_app/expenses/new'
    | '/_app/groups/$id'
    | '/_app/groups/new'
    | '/_app/settings/payments'
    | '/_app/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/payments': {
      id: '/_app/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/groups/new': {
      id: '/_app/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AppGroupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$id': {
      id: '/_app/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/new': {
      id: '/_app/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$id': {
      id: '/_app/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof AppExpensesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWalletRoute: typeof AppWalletRoute
  AppExpensesIdRoute: typeof AppExpensesIdRoute
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppGroupsIdRoute: typeof AppGroupsIdRoute
  AppGroupsNewRoute: typeof AppGroupsNewRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWalletRoute: AppWalletRoute,
  AppExpensesIdRoute: AppExpensesIdRoute,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppGroupsIdRoute: AppGroupsIdRoute,
  AppGroupsNewRoute: AppGroupsNewRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
