// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  
  // 🔑 Try multiple key names - Lovable allows SERVICE_ROLE_KEY (without SUPABASE_ prefix)
  const SUPABASE_SERVICE_ROLE_KEY = 
    process.env.SERVICE_ROLE_KEY ||           // Added to Lovable Secrets
    process.env.SUPABASE_SERVICE_ROLE_KEY ||  // Standard name (Vercel only)
    process.env.SB_SERVICE_ROLE_KEY ||        // Alternative
    process.env.LOVABLE_SUPABASE_KEY;         // Another alternative

  console.log('[Supabase Admin] 🔍 Checking environment variables...');
  console.log('[Supabase Admin] SUPABASE_URL:', SUPABASE_URL ? '✅ Present' : '❌ Missing');
  console.log('[Supabase Admin] SERVICE_ROLE_KEY:', process.env.SERVICE_ROLE_KEY ? '✅ Present' : '❌ Missing');
  console.log('[Supabase Admin] SUPABASE_SERVICE_ROLE_KEY:', process.env.SUPABASE_SERVICE_ROLE_KEY ? '✅ Present' : '❌ Missing');
  console.log('[Supabase Admin] Using key from:', Object.keys(process.env).find(key => 
    key === 'SERVICE_ROLE_KEY' || 
    key === 'SUPABASE_SERVICE_ROLE_KEY' || 
    key === 'SB_SERVICE_ROLE_KEY' || 
    key === 'LOVABLE_SUPABASE_KEY'
  ) || 'unknown');

  if (!SUPABASE_URL) {
    const message = `Missing Supabase environment variable: SUPABASE_URL. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase Admin] ❌ ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    const message = `Missing service role key. Tried: SERVICE_ROLE_KEY, SUPABASE_SERVICE_ROLE_KEY, SB_SERVICE_ROLE_KEY. Add one to Lovable Secrets or Vercel.`;
    console.error(`[Supabase Admin] ❌ ${message}`);
    throw new Error(message);
  }

  // ✅ Log key format for debugging
  if (SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_secret_')) {
    console.log('[Supabase Admin] ✅ Using sb_secret_ key format');
  } else if (SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_publishable_')) {
    console.error('[Supabase Admin] ❌ ERROR: Using publishable key instead of secret key!');
    console.error('[Supabase Admin] ❌ This will not work for admin operations.');
    console.error('[Supabase Admin] ❌ Please use the sb_secret_ key from Lovable → API → Secret keys.');
  } else {
    console.warn('[Supabase Admin] ⚠️ Unknown key format:', SUPABASE_SERVICE_ROLE_KEY.slice(0, 10) + '...');
  }

  // ✅ Log the key source
  const keySource = Object.keys(process.env).find(key => 
    key === 'SERVICE_ROLE_KEY' || 
    key === 'SUPABASE_SERVICE_ROLE_KEY' || 
    key === 'SB_SERVICE_ROLE_KEY' || 
    key === 'LOVABLE_SUPABASE_KEY'
  ) || 'unknown';
  
  console.log(`[Supabase Admin] ✅ Using service role key from: ${keySource}`);

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
